/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionStepsSection: typeof import('./src/components/ai/ActionStepsSection.vue')['default']
    AdminLayout: typeof import('./src/components/AdminLayout.vue')['default']
    AiAnalysisHeader: typeof import('./src/components/ai/AiAnalysisHeader.vue')['default']
    AiAnalysisMetaBadge: typeof import('./src/components/ai/AiAnalysisMetaBadge.vue')['default']
    AiAnalysisSidebar: typeof import('./src/components/ai/AiAnalysisSidebar.vue')['default']
    ConclusionSection: typeof import('./src/components/ai/ConclusionSection.vue')['default']
    DiagnosisSection: typeof import('./src/components/ai/DiagnosisSection.vue')['default']
    DisclaimerDialog: typeof import('./src/components/DisclaimerDialog.vue')['default']
    FloatingExportBar: typeof import('./src/components/ai/FloatingExportBar.vue')['default']
    GlobalAnnouncement: typeof import('./src/components/GlobalAnnouncement.vue')['default']
    GlobalWarning: typeof import('./src/components/GlobalWarning.vue')['default']
    OnlineCounter: typeof import('./src/components/OnlineCounter.vue')['default']
    RecommendSection: typeof import('./src/components/RecommendSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeExternalLink: typeof import('./src/components/SafeExternalLink.vue')['default']
    SkillsChatBox: typeof import('./src/components/ai/SkillsChatBox.vue')['default']
    SkillsServiceCard: typeof import('./src/components/ai/SkillsServiceCard.vue')['default']
    UniversityQa: typeof import('./src/components/UniversityQa.vue')['default']
    UserFeedbackDialog: typeof import('./src/components/UserFeedbackDialog.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VolunteerCard: typeof import('./src/components/VolunteerCard.vue')['default']
    VolunteerListPanel: typeof import('./src/components/ai/VolunteerListPanel.vue')['default']
  }
}
