CREATE TABLE IF NOT EXISTS data_year_readiness (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  province_code VARCHAR(16) NOT NULL,
  year INT NOT NULL,
  policy_ready TINYINT NOT NULL DEFAULT 0,
  score_segment_ready TINYINT NOT NULL DEFAULT 0,
  admission_plan_ready TINYINT NOT NULL DEFAULT 0,
  major_requirement_ready TINYINT NOT NULL DEFAULT 0,
  major_meta_ready TINYINT NOT NULL DEFAULT 0,
  ml_training_ready TINYINT NOT NULL DEFAULT 0,
  historical_training_ready TINYINT NOT NULL DEFAULT 1,
  recommendation_phase VARCHAR(40) NOT NULL DEFAULT 'PRE_OFFICIAL_DATA',
  latest_import_batch_id VARCHAR(120) DEFAULT NULL,
  remarks VARCHAR(500) DEFAULT NULL,
  last_checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_data_year_readiness_province_year (province_code, year),
  KEY idx_data_year_readiness_phase (recommendation_phase),
  KEY idx_data_year_readiness_checked_at (last_checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO data_year_readiness (
  province_code,
  year,
  policy_ready,
  score_segment_ready,
  admission_plan_ready,
  major_requirement_ready,
  major_meta_ready,
  ml_training_ready,
  historical_training_ready,
  recommendation_phase,
  latest_import_batch_id,
  remarks
) VALUES (
  'GZ',
  2026,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  'PRE_OFFICIAL_DATA',
  NULL,
  '2026 官方招生计划、一分一段表和模型重训尚未完成；仅允许历史数据趋势分析和缺口提示。'
) ON DUPLICATE KEY UPDATE
  policy_ready = VALUES(policy_ready),
  score_segment_ready = VALUES(score_segment_ready),
  admission_plan_ready = VALUES(admission_plan_ready),
  major_requirement_ready = VALUES(major_requirement_ready),
  major_meta_ready = VALUES(major_meta_ready),
  ml_training_ready = VALUES(ml_training_ready),
  historical_training_ready = VALUES(historical_training_ready),
  recommendation_phase = VALUES(recommendation_phase),
  latest_import_batch_id = VALUES(latest_import_batch_id),
  remarks = VALUES(remarks),
  updated_at = CURRENT_TIMESTAMP;
