-- 2026-04-10 手工补录：贵州剩余 6 所收费硬缺口
INSERT INTO `uni_official_link` (
  `school_id`,
  `school_name`,
  `source_domain`,
  `school_site`,
  `admission_site`,
  `admission_brochure_url`,
  `major_catalog_url`,
  `tuition_info_url`,
  `tuition_remark`,
  `capture_method`,
  `capture_status`,
  `last_verified_at`,
  `last_captured_at`,
  `tuition_summary`,
  `major_catalog_summary`,
  `adjustment_rule`,
  `foreign_language_rule`,
  `physical_exam_rule`,
  `single_subject_rule`,
  `parser_notes`,
  `parse_status`,
  `last_parsed_at`
) VALUES
(
  '3233',
  '贵州水利水电职业技术学院',
  'zs.gzsdzy.cn',
  'https://www.gzsdzy.cn/',
  'https://zs.gzsdzy.cn/jyweb/webIndex.zf',
  '',
  '',
  '',
  '收费信息请以招生章程原文为准，建议重点核对学费与住宿费',
  'manual',
  1,
  NOW(),
  NOW(),
  '严格按照贵州省价格主管部门批准的项目及标准执行，工程测量技术专业学费3500元/年，其余各专业学费3850元/年。',
  '',
  '',
  '',
  '',
  '',
  'manual_patch_20260410',
  1,
  NOW()
),
(
  '2569',
  '贵州职业技术学院',
  'zsw.gzvti.com',
  'https://www.gzvti.com/',
  'https://zsw.gzvti.com/',
  'https://zsw.gzvti.com/info/1042/2715.htm',
  'https://zsw.gzvti.com/info/1051/2720.htm',
  '',
  '收费信息请以招生章程原文为准，建议重点核对学费与住宿费',
  'manual',
  1,
  NOW(),
  NOW(),
  '严格按照贵州省价格主管部门批准的项目及标准执行。艺术设计、音乐表演、舞蹈表演、播音与主持、数字媒体艺术设计等专业学费标准为每生每学年7000元，其它各专业学费标准为每生每学年3850元。',
  '',
  '',
  '',
  '',
  '',
  'manual_patch_20260410',
  1,
  NOW()
),
(
  '2266',
  '贵州警察学院',
  'www.gzpc.edu.cn',
  'https://www.gzpc.edu.cn/',
  'https://www.gzpc.edu.cn/jgsz/xzbm/zsjyc_5997529/zsxx/',
  '',
  'https://www.gzpc.edu.cn/jyjx/zysz/',
  '',
  '收费信息请以招生章程原文为准，建议重点核对学费与住宿费',
  'manual',
  1,
  NOW(),
  NOW(),
  '公安学类专业4200元/年，普通本科专业3830元/年；住宿费按贵州省价格主管部门批准标准执行。',
  '本科专业',
  '',
  '',
  '在省公安厅政治部的组织领导下，配合做好公安类专业招生体检、体侧、面试工作',
  '',
  'manual_patch_20260410',
  1,
  NOW()
),
(
  '3308',
  '六盘水幼儿师范高等专科学校',
  'lpsyz.cn',
  'https://lpsyz.cn/',
  'https://lpsyz.cn/zsjy/zsxx.htm',
  '',
  '',
  '',
  '收费信息请以招生章程原文为准，建议重点核对学费与住宿费',
  'manual',
  1,
  NOW(),
  NOW(),
  '所有专业收费严格按照贵州省价格主管部门批准的项目及标准执行，详见《贵州省2025年高校招生专业目录》。',
  '六盘水幼专专业、信息安全技术应用专业、现代物业管理专业、计算机应用技术专业、人工智能技术应用专业、现代教育技术专业、舞蹈表演专业、研学旅行管理与服务专业',
  '',
  '',
  '',
  '',
  'manual_patch_20260410',
  1,
  NOW()
),
(
  '1572',
  '黔东南民族职业技术学院',
  'aoff.qdnpt.edu.cn',
  'https://www.qdnpt.edu.cn/',
  'https://www.qdnpt.edu.cn/list.thtml?cid=88',
  'https://aoff.qdnpt.edu.cn/show.thtml?id=51705',
  'https://www.qdnpt.edu.cn/page_zyjj.thtml?cid=10',
  '',
  '收费信息请以招生章程原文为准，建议重点核对学费与住宿费',
  'manual',
  1,
  NOW(),
  NOW(),
  '收费项目及标准严格按贵州省价格主管部门批准的项目及标准执行，详见《贵州省2025年高职院校分类考试招生专业目录》。',
  '',
  '',
  '',
  '',
  '',
  'manual_patch_20260410',
  1,
  NOW()
),
(
  '2268',
  '贵州航天职业技术学院',
  'www.gzhtzy.edu.cn',
  'https://www.gzhtzy.edu.cn/',
  'http://www.gzhtzy.edu.cn/zsjyc/',
  'http://www.gzhtzy.edu.cn/zsjyc/info/1122/2080.htm',
  'http://www.gzhtzy.edu.cn/zsjyc/zsjh.htm',
  '',
  '收费信息请以招生章程原文为准，建议重点核对学费与住宿费',
  'manual',
  1,
  NOW(),
  NOW(),
  '严格按照贵州省物价主管部门批准的项目及标准执行。广告艺术设计专业7000元/年/人，其他专业3850元/年/人。',
  '',
  '',
  '',
  '',
  '',
  'manual_patch_20260410',
  1,
  NOW()
)
ON DUPLICATE KEY UPDATE
  `school_name` = VALUES(`school_name`),
  `source_domain` = VALUES(`source_domain`),
  `school_site` = VALUES(`school_site`),
  `admission_site` = VALUES(`admission_site`),
  `admission_brochure_url` = VALUES(`admission_brochure_url`),
  `major_catalog_url` = VALUES(`major_catalog_url`),
  `tuition_info_url` = VALUES(`tuition_info_url`),
  `tuition_remark` = VALUES(`tuition_remark`),
  `capture_method` = VALUES(`capture_method`),
  `capture_status` = VALUES(`capture_status`),
  `last_verified_at` = VALUES(`last_verified_at`),
  `last_captured_at` = VALUES(`last_captured_at`),
  `tuition_summary` = VALUES(`tuition_summary`),
  `major_catalog_summary` = VALUES(`major_catalog_summary`),
  `adjustment_rule` = VALUES(`adjustment_rule`),
  `foreign_language_rule` = VALUES(`foreign_language_rule`),
  `physical_exam_rule` = VALUES(`physical_exam_rule`),
  `single_subject_rule` = VALUES(`single_subject_rule`),
  `parser_notes` = VALUES(`parser_notes`),
  `parse_status` = VALUES(`parse_status`),
  `last_parsed_at` = VALUES(`last_parsed_at`);
