CREATE TABLE IF NOT EXISTS `special_admission_policy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `year` INT NOT NULL DEFAULT 2026 COMMENT '招生年份',
  `category` VARCHAR(50) NOT NULL COMMENT '分类编码',
  `category_name` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `title` VARCHAR(200) NOT NULL COMMENT '政策标题',
  `summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '摘要',
  `content_md` MEDIUMTEXT NOT NULL COMMENT 'Markdown正文',
  `official_url` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '官方或权威转载链接',
  `source_name` VARCHAR(100) NOT NULL DEFAULT '贵州省招生考试院' COMMENT '来源名称',
  `source_type` VARCHAR(30) NOT NULL DEFAULT 'official' COMMENT '来源类型：official/wechat/reprint',
  `apply_start` DATE DEFAULT NULL COMMENT '报名或申报开始日期',
  `apply_end` DATE DEFAULT NULL COMMENT '报名或申报截止日期',
  `exam_time` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '考试或确认时间',
  `target_students` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '适用考生',
  `requirements` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '核心资格要求',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0草稿，1启用，2停用',
  `published_at` DATETIME DEFAULT NULL COMMENT '发布时间',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_policy_year_category_title` (`year`, `category`, `title`),
  KEY `idx_policy_category_status` (`category`, `status`, `sort_order`),
  KEY `idx_policy_year_status` (`year`, `status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='特殊类型招生政策表';

INSERT INTO `special_admission_policy`
(`year`,`category`,`category_name`,`title`,`summary`,`content_md`,`official_url`,`source_name`,`source_type`,`apply_start`,`apply_end`,`exam_time`,`target_students`,`requirements`,`sort_order`,`status`,`published_at`)
VALUES
(2026,'overview','政策总览','贵州省2026年普通高校招生工作实施细则',
'明确2026年贵州普通高校招生报名、体检、考试、志愿、划线和录取安排，特殊类型招生须加强资格审核和复查。',
'## 重点信息\n\n- 贵州2026年普通高校招生实行“3+1+2”模式。\n- 报考艺术类、体育类等专业的考生，除文化考试外，还须按要求参加相应专业考试。\n- 填报重点高校专项计划、综合评价招生、高水平运动队等专业志愿的考生，须经过相应测试选拔程序及资格审核后才具备报考资格。\n- 本科提前批A段包括军队、公安、司法、强基计划、飞行技术、综合评价、少年班、保送生、运动训练、武术与民族传统体育、残疾考生单考单招等类型。\n\n请以贵州省招生考试院后续正式公告和院校招生章程为准。',
'https://gaokao.eol.cn/gui_zhou/dongtai/202604/t20260414_2728133.shtml',
'贵州省招生考试院/教育在线转载','reprint',NULL,NULL,'2026年高考招生周期','2026年贵州普通高考考生','符合贵州省普通高考报名条件，并按所报类型完成资格审核、测试或专业考试。',100,1,'2026-04-14 00:00:00'),
(2026,'application','报名申报','2026年高考补报名及相关考试确认',
'2026年4月27日9:00至4月28日18:00开展高考补报名、英语口语考试报名、民族语言口语测试报名、英语听力第二次考试确认及考试科目修改。',
'## 重点信息\n\n- 时间：2026年4月27日9:00至4月28日18:00。\n- 涵盖：高考补报名、英语口语考试报名、民族语言口语测试报名、英语听力第二次考试确认、考试科目修改。\n- 入口：贵州招考APP或贵州省普通高校招生考试考生综合信息平台。\n\n该信息来自贵州省招生考试院官方渠道公开检索结果，页面内容上线后需继续复核官网原文。',
'https://mp.weixin.qq.com/s/ebXcFfarzbJGEQQHAaoPyQ',
'贵州省招生考试院官方微信','wechat','2026-04-27','2026-04-28','2026年4月27日9:00至4月28日18:00','需补报名或修改相关考试信息的考生','在规定时限内通过指定平台办理，逾期风险由考生自行承担。',95,1,'2026-04-26 00:00:00'),
(2026,'special_plan','专项计划','2026年普通高校招生高校专项计划资格申报',
'高校专项计划资格申报时间为2026年4月22日9:00至4月26日24:00，资格确认原则上在4月30日前完成。',
'## 重点信息\n\n- 申报时间：2026年4月22日9:00至4月26日24:00。\n- 资格确认：考生须按要求持户口簿、身份证原件和资格审查表等材料到县级招生考试机构办理。\n- 基本条件：考生本人及父亲或母亲或法定监护人户籍在实施区域农村，且考生本人具有当地连续三年以上户籍；考生具有户籍所在县高中连续三年学籍并实际就读。\n- 实施区域：公开信息显示为除贵阳市六区和遵义市两区以外的农村区域，最终以官方文件为准。',
'https://gkzxw.com/Article/202604/73370.html',
'贵州省招生考试院/高考资讯网转载','reprint','2026-04-22','2026-04-26','2026年4月30日前完成资格确认','符合高校专项计划条件的农村户籍考生','本人及监护人户籍、考生学籍和实际就读年限须满足高校专项计划要求。',90,1,'2026-04-22 00:00:00'),
(2026,'art','艺术类','贵州省2026年普通高等学校招生艺术类专业省级统考简章',
'艺术类专业省级统考简章明确考试类别、报名要求、考试安排、成绩查询和录取相关口径。',
'## 重点信息\n\n- 适用类别包括美术与设计类、音乐类、舞蹈类、播音与主持类、表演类、导演类、书法类等。\n- 考生须同时关注文化课成绩和专业统考成绩要求。\n- 艺术类可按规定兼报普通类相关批次，但艺术类和体育类之间不得兼报。\n- 统考合格线、成绩查询和后续录取控制线以贵州省招生考试院发布为准。',
'http://zsksy.guizhou.gov.cn/tzgg/202512/t20251203_89012494.html',
'贵州省招生考试院','official',NULL,NULL,'2025年12月起按类别组织','报考艺术类专业的贵州高考考生','完成高考报名和艺术类专业考试报名，并按类别参加省级统考或相关考试。',80,1,'2025-12-03 00:00:00'),
(2026,'art','艺术类','2026年普通高等学校戏曲类本科专业招生省际联考',
'戏曲类本科专业招生采取省际联考形式，涉及戏曲音乐、戏曲表演、作曲与作曲技术理论等专业方向。',
'## 重点信息\n\n- 招生采取省际联考形式。\n- 报考对象为符合贵州省2026年高考报名条件且具有一定戏曲艺术基础的考生。\n- 考生需同时完成文化考试报名和专业考试报名。\n- 录取时一般要求高考文化课成绩达到贵州省规定要求，专业成绩合格后依据联考专业成绩择优录取。',
'http://zsksy.guizhou.gov.cn/tzgg/202511/t20251127_88988833.html',
'贵州省招生考试院','official',NULL,NULL,'原则上安排在2025年12月至2026年2月','报考戏曲类本科专业的艺术类考生','符合贵州高考报名条件，并具有相应戏曲艺术基础。',75,1,'2025-11-27 00:00:00'),
(2026,'sports','体育类','2026年普通高校体育类专业考试招生提示',
'体育类考生需同时达到高考文化成绩和体育专业成绩要求，首选物理或历史均可填报体育类招生专业。',
'## 重点信息\n\n- 体育类本科划线按首选科目物理、历史分别划定。\n- 填报体育类专业志愿的考生，高考总成绩和专业成绩均应达到录取控制分数线。\n- 普通类不得兼报艺术类和体育类，艺术类和体育类之间不得兼报。\n- 体育类可按规定兼报普通类部分批次，具体以当年志愿填报系统和招生计划为准。',
'https://gaokao.eol.cn/gui_zhou/dongtai/202604/t20260414_2728133.shtml',
'贵州省招生考试院/教育在线转载','reprint',NULL,NULL,'以省级专业考试和高考时间为准','报考体育类专业的贵州高考考生','文化成绩和体育专业成绩均须达到相应控制线。',70,1,'2026-04-14 00:00:00'),
(2026,'qualification','资格条件','少数民族加分、国家专项、地方专项、随迁子女等资格申报',
'相关资格申报已在前期组织，涉及少数民族加分、国家专项计划、地方专项计划、外来人员随迁子女资格等。',
'## 重点信息\n\n- 申报类别：少数民族加分、国家专项计划、地方专项计划、外来人员随迁子女资格等。\n- 公开检索结果显示申报时间为2025年12月1日至12月10日。\n- 相关资格直接影响可填报志愿类别和投档资格，考生应核对报名系统中的资格审核结果。\n- 未通过资格审核的考生不得填报对应专项或资格类志愿。',
'https://mp.weixin.qq.com/s/ebXcFfarzbJGEQQHAaoPyQ',
'贵州省招生考试院官方微信','wechat','2025-12-01','2025-12-10','以县级招生考试机构审核安排为准','申请加分、专项计划或随迁子女资格的考生','按类别提交材料并通过资格审核。',65,1,'2025-12-01 00:00:00'),
(2026,'early_batch','提前批特殊类型','强基计划、综合评价、高水平运动队等特殊类型志愿资格',
'强基计划、综合评价、高水平运动队等须通过相应测试选拔程序及资格审核后才具备报考资格。',
'## 重点信息\n\n- 相关类型通常纳入本科提前批A段或按教育部、院校和贵州省规定投档录取。\n- 包括强基计划、飞行技术招生、综合评价招生、少年班、保送生、运动训练、武术与民族传统体育专业招生、残疾考生单考单招、应急消防单独招生、职教师资单独招生等。\n- 院校特殊类型考试招生办法须符合教育部及生源省份相关规定，并不得与招生章程内容相违背。\n- 考生务必同时核对贵州省资格要求和目标院校招生简章。',
'https://gaokao.eol.cn/gui_zhou/dongtai/202604/t20260414_2728133.shtml',
'贵州省招生考试院/教育在线转载','reprint',NULL,NULL,'以教育部、贵州省和招生院校安排为准','报考强基、综评、高水平运动队等特殊类型的考生','完成院校测试选拔程序及贵州省相应资格审核。',60,1,'2026-04-14 00:00:00')
ON DUPLICATE KEY UPDATE
  `summary`=VALUES(`summary`),
  `content_md`=VALUES(`content_md`),
  `official_url`=VALUES(`official_url`),
  `source_name`=VALUES(`source_name`),
  `source_type`=VALUES(`source_type`),
  `apply_start`=VALUES(`apply_start`),
  `apply_end`=VALUES(`apply_end`),
  `exam_time`=VALUES(`exam_time`),
  `target_students`=VALUES(`target_students`),
  `requirements`=VALUES(`requirements`),
  `sort_order`=VALUES(`sort_order`),
  `status`=VALUES(`status`),
  `published_at`=VALUES(`published_at`);
